2025-03-10 09:13:50,344 INFO    MainThread:2096 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-03-10 09:13:50,344 INFO    MainThread:2096 [wandb_setup.py:_flush():68] Configure stats pid to 2096
2025-03-10 09:13:50,344 INFO    MainThread:2096 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Talmid\.config\wandb\settings
2025-03-10 09:13:50,344 INFO    MainThread:2096 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Talmid\Desktop\AI\Mancala\wandb\settings
2025-03-10 09:13:50,344 INFO    MainThread:2096 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-03-10 09:13:50,345 INFO    MainThread:2096 [wandb_init.py:_log_setup():523] Logging user logs to C:\Users\Talmid\Desktop\AI\Mancala\wandb\run-20250310_091350-Mancala 12\logs\debug.log
2025-03-10 09:13:50,345 INFO    MainThread:2096 [wandb_init.py:_log_setup():524] Logging internal logs to C:\Users\Talmid\Desktop\AI\Mancala\wandb\run-20250310_091350-Mancala 12\logs\debug-internal.log
2025-03-10 09:13:50,346 INFO    MainThread:2096 [wandb_init.py:init():641] calling init triggers
2025-03-10 09:13:50,346 INFO    MainThread:2096 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'name': 'Mancala 12', 'checkpoint': 'Data/Player1/checkpoint12.pth', 'learning_rate': 0.001, 'epochs': 60000, 'start_epoch': 0, 'decay': 5000, 'gamma': 0.99, 'batch_size': 64, 'C': 200, 'Model': 'DQN(\n  (linear1): Linear(in_features=16, out_features=128, bias=True)\n  (linear2): Linear(in_features=128, out_features=64, bias=True)\n  (output): Linear(in_features=64, out_features=1, bias=True)\n)', 'device': 'cpu'}
2025-03-10 09:13:50,346 INFO    MainThread:2096 [wandb_init.py:init():674] starting backend
2025-03-10 09:13:51,739 INFO    MainThread:2096 [wandb_init.py:init():678] sending inform_init request
2025-03-10 09:13:51,770 INFO    MainThread:2096 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-03-10 09:13:51,771 INFO    MainThread:2096 [wandb_init.py:init():693] backend started and connected
2025-03-10 09:13:51,773 INFO    MainThread:2096 [wandb_init.py:init():786] updated telemetry
2025-03-10 09:13:51,841 INFO    MainThread:2096 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-03-10 09:13:51,910 WARNING MsgRouterThr:2096 [router.py:message_loop():75] message_loop has been closed
2025-03-10 09:13:56,846 ERROR   MainThread:2096 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 821, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Talmid\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
